language: python
python:
    - 3.5
    - 3.6

install:
    - sudo apt-get update
    # Install Conda
     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
      # Useful for debugging any issues with conda
    - conda info -a
    - conda create -n var2dm python=$TRAVIS_PYTHON_VERSION numpy scipy
    nose matplotlib pylint pycodestyle pydocstyle
    - conda install -c theochem gbasis
    - conda install -c theochem iodata
    - source active var2DM

    # Install Dependencies
    #- pip install numpy scipy nose matplotlib
    #- pip install pylint, pycodestyle pydocstyle

script:
    - nosetests --with-coverage --cover-package=densitymatrices -v ./var2DM/
    - pylint ./var2DM/ --errors-only
    - pycodestyle ./var2DM/ --max-line-length=100
    - pydocstyle ./var2DM/

notifications:
  email: false
